steps:
# 1. Build Docker image
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - us-central1-docker.pkg.dev/$PROJECT_ID/fastapi-repo/fastapi:latest
    - .

# 2. Push image
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - us-central1-docker.pkg.dev/$PROJECT_ID/fastapi-repo/fastapi:latest

# 3. Deploy to GKE
- name: gcr.io/cloud-builders/kubectl
  env:
    - CLOUDSDK_COMPUTE_ZONE=us-central1-a
    - CLOUDSDK_CONTAINER_CLUSTER=fastapi-cluster
  args:
    - apply
    - -f
    - deployment.yaml

- name: gcr.io/cloud-builders/kubectl
  env:
    - CLOUDSDK_COMPUTE_ZONE=us-central1-a
    - CLOUDSDK_CONTAINER_CLUSTER=fastapi-cluster
  args:
    - apply
    - -f
    - service.yaml
